name: HawkScan
on:
  push:
  
jobs:
  hawkscan:
    name: HawkScan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Run HawkScan
        run: |
            docker run -v "$(pwd):/hawk" -e HAWK_API_KEY=${{ secrets.HAWK_API_KEY }} stackhawk/hawkscan:latest scan /hawk/stackhawk.yml

      - name: Create HawkScan Configuration File
        run: |
          echo "app:" > stackhawk.yml
          echo "  applicationId: 0d359688-db79-4213-b693-7712ca223dd7" >> stackhawk.yml
          echo "  host: http://localhost:8000" >> stackhawk.yml
          echo "  env: Development" >> stackhawk.yml

      - name: Run HawkScan
        run: |
          hawk scan --api-key ${{ secrets.HAWK_API_KEY }} --config stackhawk.yml
